# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
 check_list:
    docker:
    - image: node:latest
    steps:
    - run:
        command: npm install -g iptv-checker
        name: install package
    - run:
        command: apt-get update
        name: update packages list
    - run:
        command: apt-get install -y ffmpeg
        name: install prereqs

workflows:
  check_list:
    jobs:
    - check_list
  version: 2


